swagger: "2.0"
info:
  title: "Midterm to-do List API"
  description: "API"
  version: "1.0.0"
host: cloud-app-dev-yessimseit2.appspot.com
schemes:
  - "https"
paths:
  /api/tasks:
    get:
      summary: "Get all tasks"
      operationId: "getTasks"
      responses:
        200:
          description: "A list of tasks"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                task:
                  type: "string"
                done:
                  type: "boolean"
    post:
      summary: "Add a new task"
      operationId: "addTask"
      parameters:
        - name: "task"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              task:
                type: "string"
              done:
                type: "boolean"
      responses:
        201:
          description: "Task created"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
              task:
                type: "string"
              done:
                type: "boolean"

  /tasks/{task_id}:
    put:
      summary: "Update a task"
      operationId: "updateTask"
      parameters:
        - name: "task_id"
          in: "path"
          required: true
          type: "integer"
        - name: "task"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              task:
                type: "string"
              done:
                type: "boolean"
      responses:
        200:
          description: "Task updated"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
              task:
                type: "string"
              done:
                type: "boolean"
    delete:
      summary: "Delete a task"
      operationId: "deleteTask"
      parameters:
        - name: "task_id"
          in: "path"
          required: true
          type: "integer"
      responses:
        200:
          description: "Task deleted"
        404:
          description: Todo not found
      security:
        - api_key: []
  securityDefinitions:
  api_key:
    type: apiKey
    name: api-key
    in: header